services:
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080
  db:
    image: postgres
    container_name: database_great
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db_great 
    volumes:
      - ./pgdata:/data/postgres

  backend:
    image: backend:latest
    restart: always
    ports:
      - 8080:8080
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_great?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    - SPRING.DATASOURCE_USERNAME=docker 
    - SPRING.DATASOURCE_PASSWORD=docker
  frontend:
    image: frontend:latest
    restart: always
    ports:
      - 3000:3000