import Head from 'next/head'
import { Layout } from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>CRUD Usuários GREAT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout />
    </div>
  )
}
