import Head from 'next/head'
import Router from 'next/router';
import { useEffect } from 'react';
import { Layout } from '../components';

export default function Home() {

  useEffect(() => {
    const { pathname } = Router;
    if(pathname == '/' ){
      Router.push('/consultas/usuarios');
    }
 });

  return (
    <div>
      <Head>
        <title>CRUD Usuários GREAT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </div>
  )
}
